# Generated by Django 4.2 on 2026-03-15 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('clinics', '0001_initial'),
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmodule',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_modules', to='users.patient'),
        ),
        migrations.AddField(
            model_name='clinicmodule',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_modules', to='clinics.clinic'),
        ),
        migrations.AddField(
            model_name='clinicmodule',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_modules', to='modules.module'),
        ),
        migrations.AlterUniqueTogether(
            name='patientmodule',
            unique_together={('patient', 'clinic', 'module')},
        ),
        migrations.AlterUniqueTogether(
            name='clinicmodule',
            unique_together={('clinic', 'module')},
        ),
    ]
