# Generated by Django 4.2 on 2026-03-18 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientModule',
        ),
    ]
