# Generated by Django 4.2 on 2026-03-18 13:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        ('users', '0003_delete_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('med_name', models.CharField(max_length=150)),
                ('med_form', models.CharField(max_length=50)),
                ('med_unit', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PatientMedication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('dosage', models.CharField(max_length=50)),
                ('frequency', models.CharField(choices=[('ONCE', 'Once'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], max_length=10)),
                ('frequency_data', models.JSONField(blank=True, default=dict)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_medications', to='clinics.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_medications', to='users.staff')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_medications', to='medications.medication')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_medications', to='users.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicMedication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_medications', to='clinics.clinic')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_medications', to='medications.medication')),
            ],
            options={
                'unique_together': {('clinic', 'medication')},
            },
        ),
    ]
