# Generated by Django 4.2 on 2026-03-18 14:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_admin'),
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('taken_at', models.DateTimeField()),
                ('dosage_taken', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('TAKEN', 'Taken'), ('SKIPPED', 'Skipped'), ('DELAYED', 'Delayed')], max_length=10)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_logs', to='users.patient')),
                ('patient_medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='medications.patientmedication')),
            ],
        ),
    ]
