# Generated by Django 4.2 on 2026-03-15 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='primary_clinic',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='primary_doctor',
        ),
    ]
