# Generated by Django 4.2 on 2026-03-15 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_patient_primary_clinic_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
