# Generated by Django 4.2 on 2026-03-15 11:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clinic_name', models.CharField(max_length=255, unique=True)),
                ('clinic_url', models.URLField(unique=True)),
                ('clinic_image_url', models.URLField(blank=True, null=True)),
                ('is_research_clinic', models.BooleanField(default=False)),
            ],
        ),
    ]
